<?
define('BW_NON_WORD_PATTERN', '[\W_ ]');

// Types of replacements.
define('BW_STRING',        1);
define('BW_REGEX',         2);

define('BW_REALLYBAD',     1);
define('BW_RELIGIOUS',     2);
define('BW_UNSAFE',        3);
define('BW_SEX',           4);
define('BW_POLITICAL',     5);
define('BW_HATEFUL',       6);
define('BW_ANATOMY',       7);
define('BW_SUSPICIOUS',    8);
define('BW_INAPPROPRIATE', 9);

$FILTER_PREVENT = array(BW_REALLYBAD, BW_RELIGIOUS, BW_SEX, BW_POLITICAL, BW_HATEFUL, BW_ANATOMY);
$FILTER_NOTIFY  = array(BW_UNSAFE);

$LETTERS = array('1'  => 'l',
                 '7'  => 't',
                 '3'  => 'e',
                 '5'  => 's',
                 '8'  => 'b',
                 '0'  => 'o',
                 '4'  => 'a',
                 'z'  => 's',
                 '6'  => 'g',
//                 '_'  => '',
//                 ' '  => '',
                 'ph' => 'f');

$_WORDS[BW_INAPPROPRIATE][BW_STRING] = array('beer',
                                            'vodka',
                                            'wine',
                                            'booze',
                                            'liquor',
                                            'whiskey',
                                            'tequilla');
$_WORDS[BW_INAPPROPRIATE][BW_REGEX]  = array();

$_WORDS[BW_SUSPICIOUS][BW_STRING] = array();
$_WORDS[BW_SUSPICIOUS][BW_REGEX]  = array('[a-z]{1}\W+[a-z]{1}\W+[a-z]{1}\W+[a-z]{1}',
                                         '\W+[a-z]{1}\W+[a-z]{1}\W+[a-z]{1}');

$_WORDS[BW_REALLYBAD][BW_STRING] = array("fuck",
                                        "shit",
                                        "cock",
                                        "cunt",
                                        "asshole",
                                        "dick",
                                        "boobs",
                                        "penis",
                                        "fuck",
                                        "phuck",
                                        "fux",
                                        "phux",
                                        "fuk",
                                        "fuc",
                                        "ucker",
                                        "phock",
                                        "fock",
                                        "fok",
                                        "phok",
                                        "fuq",
                                        "phuq",
                                        "cunt",
                                        "dick",
                                        "arse",
                                        "pussy",
                                        "prick",
                                        "bastard",
                                        "piss",
                                        "crap",
                                        "shyt"); 

$_WORDS[BW_REALLYBAD][BW_REGEX]  = array("(ph|f).{1,3}c{1,3}k{1,3}",
                                        "(ph|f)(o|u){1,3}q{1,3}",
                                      	"(ph|f)c{1,3}u{1,3}c{0,3}k{0,3}",
                                        "fkn?[uie]+n",
                                        "ph(u|e|a)k",
                                        "fker",
                                        "fuk",
                                        "fuc",
                                        "fug",
                                        "kcuf",
                                        "ckuf",
                                        "fck",
                                        "f.*?[ck]+me",
                                        "f.{1,9}?you",
                                        "h[i1l]+(gh)?on",
                                        "r[ea]+m+e",
                                        "ben.*?o.?v.r",
                                        "pen[i1l]+[s5]+",
                                        "n[aeiou]+gger",
                                        "n[aeiou]+gga",
                                        "ni[69]+[aie]r",
                                      	"sh[ia1l]{1,3}t",
                                      	"[kc]unt",
                                      	"pus+[yi1l]+",
                                      	"clea?v[ea]ge",
                                      	"d[i1ly]+ke",
                                      	"perv(ert)?",
                                        "g[il1]+m+e",
                                        "g[il1]+veme",
                                      	"cum",
                                      	"d[i1ly]+ck?",
                                      	"orgas.",
                                      	"[sc][yi]b[aeui]*r",
                                      	"ejacu....",
                                      	"sp[ue]rm",
                                      	"pen(e|a)trat",
                                      	"v(i|a)g.na?",
                                      	"throb",
                                      	"mast.rb.t.",
                                      	"can+[ai1l]+b[i1l]+s",
                                      	"hero[i1l]+n",
                                      	"wank",
                                      	"prost[i1laey]+t.?",
                                      	"b[ieoyal1]+tch",
                                        "b[i1l]+z.*?t?ch",
                                      	"nude",
                                      	"[ou]sama",
                                      	"lad[ei1l]+n",
                                      	"a[sz]+hol",
                                      	"w?hore",
                                        "hell[^o]",
                                      	"b[ou]l+[ou]cks",
                                        "b[ou]l+[ou]cs",
                                        "b[ou]l+[ou]ks",
                                      	"su[i1l]+c[i1l]+d.?",
                                      	"org[i1lye]+",
                                      	"pr[i1l]+ck",
                                      	"n[i1l]+p+le",
                                      	"blowjob",
                                      	"test[i1l]+c..?",
                                      	".e[zs]t[i1l]+cl.?",
                                        ".oo+b[i1l]+es",
                                        "t[i1l]+t+i?es",
                                        "t[i1l]+t+y",
                                      	"[ck]o[ckq]+",
                                      	"cam.?ltoe",
                                      	"circlej[aeio]rk",
                                      	"crap",
                                      	"cun+[i1l]+ng",
                                      	"felt?ch",
                                      	"hoot.?rs",
                                      	"qu[i1l]+f",
                                      	"que+(f|ph)",
                                      	"kwe+f",
                                      	"nutsa[ck]+",
                                      	"n[iy]m[phf]+o?",
                                      	"po+ntang",
                                      	"que+r",
                                      	"qu[i1l]+m",
                                      	"r[i1l]+mjob",
                                      	"sk[i1l]+nflut",
                                      	"swordswal+ow",
                                      	"span(.*?)monk..",
                                      	"we+.n[i1l]+?er?",
                                      	"bast.rd",
                                      	"jackoff?",
                                      	"an[ui]s",
                                      	"an[auie]l",
                                      	"scro[dt]+.m",
                                      	"p[i1l]+[sz]+",
                                      	"[ck]oon",
                                      	"kike",
                                      	"ch[i1l]+nk",
                                      	"homo",
                                      	"hoo[ck]e?r",
                                      	"nobjo[ck].?.?",
                                        "sh?lut",
                                        "d[il1]ck",
                                        "we[t7]+ ?dr[ea]+m",
                                        "b[ea]+rded.?clam",
                                        "b[ea]+v[ea]+r",
                                        "taco",
                                        "no[ck]+ed ?up",
                                        "b[ea]+f ?[ei]nj",
                                        "wh?a[ck]+",
                                        "e[xc]+sta[sc]+y",
                                        "s[i1l]+x(.*?)n[ei1l]+n",
                                        "e[ea]+tme",
                                        "y[eai]st[i1l]+nfect",
                                        "n[ae]y?[ck]+[ei]d",
                                        "[i1l]+n[cs]+est",
                                        "lo.?l[ie]ta",
                                        "poo$",
                                        "fore?s[kc]+in",
                                        "bop(.*)b[au]+lon",
                                        "ba[ck]+door",
                                        "g[uoe]+ldensho(.*?)r",
                                        "d[i1l]+ng(.*?)berr",
                                        "dol+[aeu]r",
                                        "ped(.*?)f[i1l]+e",
                                        "n[ea]+cr[aeiou]+f[aeiou]+l",
                                        "^www",
                                        "com$",
                                        "net$",
                                        "org$",
                                        "(k|c)astrat",
                                        "de(c|k)apitat",
                                        "\d+some",
                                        "pee$",
                                        "^pee",
                                        "fur+p[i1l]*e",
                                        "l[i1l]+[ck]+(your|ur|my)",
                                        "(j|g)[ue]+r+b[iea]+l",
                                        "crot?ch",
                                        "pr[il1]+v[ea]te",
                                        "puss$",
                                        "h[eu]r+shey?",
                                        "ass[^aeiouy]");


$_WORDS[BW_RELIGIOUS][BW_STRING] = array("jesus",
                                        "christ",
                                        "allah",
                                        "islam",
                                        "muslim",
                                        "muslam",
                                        "jew",
                                        "satan",
                                        "lucifer",
                                        "jihad",
                                        "god",
                                        "devil");
$_WORDS[BW_RELIGIOUS][BW_REGEX]  = array();


$_WORDS[BW_UNSAFE][BW_STRING]  = array("lesbian",
                                      "homosexual",
                                      "cocaine",
                                      "heroin",
                                      "marijuana",
                                      "suicide",
                                      "hentai",
                                      "panty",
                                      "butt",
                                      "suck",
                                      "babe",
                                      "pimp",
                                      "juic",
                                      "pig",
                                      "sex",
                                      "cypher",
                                      "murder",
                                      "kill",
                                      "death",
                                      "bong",
                                      "pipe",
                                      "crack", 
                                      "smeg",
                                      "wench",
                                      "whench",
                                      "skank",
                                      "mofo",
                                      "easy",
                                      "brothel",
                                      "sodom",
                                      "sodum",
                                      "defecate",
                                      "douche",
                                      "doosh",
                                      "dousch",
                                      "doosch",
                                      "flatul",
                                      "urine",
                                      "feces",
                                      "smega",
                                      "toilet",
                                      "vomit",
                                      "scum",
                                      "spleef",
                                      "spliff",
                                      "fart",
                                      "phart",
                                      "vicodin",
                                      "oxycotin",
                                      "acid",
                                      "joint",
                                      "blunt",
                                      "roofie",
                                      "viagra",
                                      "pot",
                                      "finger",
                                      "porn",
                                      "pron",
                                      "jerk",
                                      "thong",
                                      "retard",
                                      "hiv",
                                      "aids",
                                      "xtc",
                                      "drunk",
                                      "incest",
                                      "lolita",
                                      "sh1t",
                                      "bite",
                                      "wtf",
                                      "omg",
                                      "poop",
                                      "molest",
                                      "crank",
                                      "kkk",
                                      "spic",
                                      "turd",
                                      "abortion",
                                      "aborsh",
                                      "abort",
                                      "aboresh",
                                      "pants",
                                      "casanov",
                                      "vice",
                                      "peddler",
                                      "beat",
                                      "smoker",
                                      "smocer",
                                      "smocher",
                                      "heshe",
                                      "sappho",
                                      "fudg",
                                      "pinchaloaf",
                                      "takeadump",
                                      "doodoo",
                                      "doodie",
                                      "doody",
                                      "cack",
                                      "hairpie",
                                      "lingus",
                                      "hardcor",
                                      "hardkor",
                                      "bugger",
                                      "buger",
                                      "bondag",
                                      "strip",
                                      "boy",
                                      "girl",
                                      "male",
                                      "female",
                                      "bra",
                                      "gstring",
                                      "stalker",
                                      "gimp",
                                      "shet",
                                      "furken",
                                      "upyour",
                                      "spreadyourlegs",
                                      "babyonameathok",
                                      "iwannacome",
                                      "fist",
                                      "come",
                                      "lick",
                                      "touch",
                                      "upur",
                                      "upyour",
                                      "upmy",
                                      "stoner",
                                      "rectum",
                                      "krak",
                                      "sausage",
                                      "wannafeel",
                                      "wantofeel",
                                      "wetslit",
                                      "wetmamma",
                                      "wetnips",
                                      "slave",
                                      "porchmonkey",
                                      "spearchucker",
                                      "jig",
                                      "spook",
                                      "coon",
                                      "hooka",
                                      "ookah",
                                      "imaho",
                                      "uraho",
                                      "flog",
                                      "spade",
                                      "darkie",
                                      "slant",
                                      "shaved",
                                      "tarbab",
                                      "admin");
$_WORDS[BW_UNSAFE][BW_REGEX] = array();


$_WORDS[BW_POLITICAL][BW_STRING] = array("hitler",
                                        "saddam",
                                        "sadam",
                                        "iraq",
                                        "iran",
                                        "nazi",
                                        "osama",
                                        "laden");
$_WORDS[BW_POLITICAL][BW_REGEX]  = array();


$_WORDS[BW_HATEFUL][BW_STRING] = array("nigger",
                                      "niger",
                                      "niga",
                                      "nigs",
                                      "fag",
                                      "aggot",
                                      "gay",
                                      "kike",
                                      "chink",
                                      "gook",
                                      "dyke",
                                      "queer",
                                      "rape",
                                      "homo",
                                      "bitch",
                                      "whor",
                                      "whoar",
                                      "wank",
                                      "slut",
                                      "wetback",
                                      "damn");
$_WORDS[BW_HATEFUL][BW_REGEX]  = array();



$_WORDS[BW_ANATOMY][BW_STRING] = array("dyck",
                                      "tongue",
                                      "penis",
                                      "vagina",
                                      "breast",
                                      "nude",
                                      "clit",
                                      "vulva",
                                      "testicle",
                                      "foreskin",
                                      "anus",
                                      "hooter",
                                      "cameltoe",
                                      "nutsack",
                                      "scrotum",
                                      "prostate",
                                      "sperm",
                                      "sprm",
                                      "cleavage",
                                      "cock",
                                      "nipple",
                                      "pubic",
                                      "twat",
                                      "hung",
                                      "endowed",
                                      "busty",
                                      "poon",
                                      "twat",
                                      "butt",
                                      "genitals",
                                      "genitalia",
                                      "menstrua",
                                      "pregnant",
                                      "testalgia",
                                      //"ass",
                                      "manroot",
                                      "worm",
                                      "schlong",
                                      "shlong",
                                      "dong",
                                      "skin",
                                      "1eye",
                                      "oneye",
                                      "nuts",
                                      "wad",
                                      "cojones",
                                      "jewels",
                                      "sack",
                                      "cootch",
                                      "honkers",
                                      "knob",
                                      "jugs",
                                      "melons",
                                      "giblets",
                                      "muff",
                                      "booty",
                                      "bootie");
$_WORDS[BW_ANATOMY][BW_REGEX]   = array("boo+b");



$_WORDS[BW_SEX][BW_STRING] = array(//SEX RELATED
                              "cum",
                              "fornicate",
                              "fornicator",
                              "pervert",
                              "cyber",
                              "ejaculate",
                              "orgasm",
                              "splooge",
                              "prostitute",
                              "screw",
                              "suck",
                              "69",
                              "quif",
                              "rimjob",
                              "hooker",
                              "circlejerk",
                              "cunnilingus",
                              "felatio",
                              "foreplay",
                              "forplay",
                              "nympho",
                              "skinflute",
                              "jackoff",
                              "blowjob",
                              "dildo",
                              "orgy",
                              "semen",
                              "horny",
                              "horney",
                              "hornie",
                              "facial",
                              "a2m",
                              "shag",
                              "xxx",
                              "virgin",
                              "jiz",
                              "boner",
                              "stify",
                              "stifie",
                              "hard",
                              "laid",
                              "syphilis",
                              "gonorrhea",
                              "intercourse",
                              "oral",
                              "whacker",
                              "jism",
                              "spunk",
                              "clap",
                              "dose",
                              "milf",
                              "bj",
                              "hump",
                              "bang",
                              "carpetmuncher",
                              "muncher",
                              "princealbert",
                              "reacharound",
                              "condom",
                              "eatme",
                              "tantric",
                              "handjob",
                              "strapon",
                              "spank");
$_WORDS[BW_SEX][BW_REGEX]  = array("woo+d");



  
                     
                        

                     
?>