
var dz=document;
dz.writeln("<html>");
dz.writeln("");
dz.writeln("<head>");
dz.writeln("");
dz.writeln("<script type=\"text/javascript\" src=\"http://partner.googleadservices.com/gampad/google_service.js\">");
dz.writeln("<\/script>");
dz.writeln("<script type=\"text/javascript\">");
dz.writeln("  GS_googleAddAdSenseService(\"ca-pub-0849196286564970\");");
dz.writeln("  GS_googleEnableAllServices();");
dz.writeln("<\/script>");
dz.writeln("<script type=\"text/javascript\">");
dz.writeln("  GA_googleAddSlot(\"ca-pub-0849196286564970\", \"728x90ValueClickRedirect\");");
dz.writeln("<\/script>");
dz.writeln("<script type=\"text/javascript\">");
dz.writeln("  GA_googleFetchAds();");
dz.writeln("<\/script>");
dz.writeln("");
dz.writeln("</head>");
dz.writeln("");
dz.writeln("<body>");
dz.writeln("");
dz.writeln("");
dz.writeln("<script type=\"text/javascript\">");
dz.writeln("  GA_googleFillSlot(\"728x90ValueClickRedirect\");");
dz.writeln("<\/script>");
dz.writeln("");
dz.writeln("</body>");
dz.writeln("");
dz.writeln("</html>");
dz.writeln("");
